# Generated by Django 4.2.1 on 2023-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=100)),
                ("images", models.ImageField(upload_to="cake")),
            ],
        ),
        migrations.RemoveField(
            model_name="cartitems",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitems",
            name="pizza",
        ),
        migrations.RemoveField(
            model_name="pizza",
            name="category",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItems",
        ),
        migrations.DeleteModel(
            name="Pizza",
        ),
        migrations.DeleteModel(
            name="PizzaCategory",
        ),
    ]
